import { Colaborador } from "./models/Colaborador.js"

async function initData() {
    try {
        await Colaborador.bulkCreate([
            {
                nombres: "SEBASTIAN",
                apellidos: "PINEDO",
                cargo: 'JEFE DE OPERACIONES',
                activo: true,
                has_signin: true,
                usuario: "operaciones",
                contrasena: "$2b$10$Dp/xNQrurOqvZv.1JRBAUO89b2ZXNfWPy7fT/HFW.OO2PL4Nwn6TO",
                permisos: [
                    "vProveedores",
                    "vProveedores_crear",
                    "vProveedores_editar",
                    "vProveedores_eliminar",
                    "vProveedores_editarBulk",
                    "vProveedores_eliminarBulk",
                    "vArticuloCategorias",
                    "vArticuloCategorias_crear",
                    "vArticuloCategorias_editar",
                    "vArticuloCategorias_eliminar",
                    "vArticulos",
                    "vArticulos_crear",
                    "vArticulos_importar",
                    "vArticulos_editar",
                    "vArticulos_eliminar",
                    "vArticulos_clonar",
                    "vArticulos_kardex",
                    "vArticulos_ajusteStock",
                    "vArticulos_editarBulk",
                    "vArticulos_eliminarBulk",
                    "vPrecioListas",
                    "vPrecioListas_crear",
                    "vPrecioListas_editar",
                    "vPrecioListas_eliminar",
                    "vPrecioListaItems",
                    "vPrecioListaItems_crear",
                    "vPrecioListaItems_editar",
                    "vPrecioListaItems_eliminar",
                    "vCompraPedidos",
                    "vCompraPedidos_crear",
                    "vCompraPedidos_ver",
                    "vCompraPedidos_editar",
                    "vCompraPedidos_anular",
                    "vCompraPedidos_generarPdf",
                    "vCompraPedidos_ingresarMercaderia",
                    "vCompras",
                    "vCompras_crear",
                    "vCompras_ver",
                    "vCompras_anular",
                    "vCompraItems",
                    "vCompraItems_inspeccion",
                    "vClientes",
                    "vClientes_crear",
                    "vClientes_editar",
                    "vClientes_eliminar",
                    "vProductoCategorias",
                    "vProductoCategorias_crear",
                    "vProductoCategorias_editar",
                    "vProductoCategorias_eliminar",
                    "vProductosTerminados",
                    "vProductosTerminados_crear",
                    "vProductosTerminados_crearCombo",
                    "vProductosTerminados_importar",
                    "vProductosTerminados_editar",
                    "vProductosTerminados_eliminar",
                    "vProductosTerminados_clonar",
                    "vProductosTerminados_kardex",
                    "vProductosTerminados_ajusteStock",
                    "vProductosTerminados_editarBulk",
                    "vProductosTerminados_eliminarBulk",
                    "vReceta",
                    "vReceta_crear",
                    "vReceta_editar",
                    "vReceta_eliminar",
                    "vPtsIngresos",
                    "vPtsIngresos_verCuarentena",
                    "vPtsIngresos_ingresarPts",
                    "vVentaPedidos",
                    "vVentaPedidos_verProductosPedidos",
                    "vVentaPedidos_crear",
                    "vVentaPedidos_ver",
                    "vVentaPedidos_editar",
                    "vVentaPedidos_anular",
                    "vVentaPedidos_entregarMercaderia",
                    "vVentas",
                    "vVentas_crear",
                    "vVentas_ver",
                    "vVentas_anular",
                    "vVentas_controlDespacho",
                    "vProgramaFiltrantes",
                    "vProgramaFiltrantes_verProductosPedidos",
                    "vProgramaFiltrantes_crear",
                    "vProgramaFiltrantes_ver",
                    "vProgramaFiltrantes_editar",
                    "vProgramaFiltrantes_eliminar",
                    "vProgramaFiltrantes_salidaInsumos",
                    "vProgramaFiltrantes_productosCuarentena",
                    "vProgramaGranel",
                    "vProgramaGranel_verProductosPedidos",
                    "vProgramaGranel_crear",
                    "vProgramaGranel_ver",
                    "vProgramaGranel_editar",
                    "vProgramaGranel_eliminar",
                    "vProgramaGranel_salidaInsumos",
                    "vProgramaGranel_productosCuarentena",
                    "vProgramaLuxury",
                    "vProgramaLuxury_verProductosPedidos",
                    "vProgramaLuxury_crear",
                    "vProgramaLuxury_ver",
                    "vProgramaLuxury_editar",
                    "vProgramaLuxury_eliminar",
                    "vProgramaLuxury_salidaInsumos",
                    "vProgramaLuxury_productosCuarentena",
                    "vProduccionHistorial",
                    "vProduccionHistorial_ver",
                    "vProduccionHistorial_salidaInsumos",
                    "vProduccionHistorial_controlPesos",
                    "vProduccionHistorial_controlPpc",
                    "vProduccionHistorial_productosCuarentena",
                    "vProduccionHistorial_productosTerminados",
                    "vProductosCuarentena",
                    "vProductosCuarentena:liberar_lote",
                    "vFormatosBpm",
                    "vFormatosBpm:crear",
                    "vFormatosBpm:ver",
                    "vFormatosBpm:editar",
                    "vFormatosBpm:eliminar",
                    "vFormatosPhs",
                    "vFormatosPhs:crear",
                    "vFormatosPhs:ver",
                    "vFormatosPhs:editar",
                    "vFormatosPhs:eliminar",
                    "vFormatosHaccp",
                    "vFormatosHaccp:crear",
                    "vFormatosHaccp:ver",
                    "vFormatosHaccp:editar",
                    "vFormatosHaccp:eliminar",
                    "vInspecciones",
                    "vInspecciones_crear",
                    "vInspecciones_editar",
                    "vInspecciones_eliminar",
                    "vRegistrosSanitarios",
                    "vRegistrosSanitarios_crear",
                    "vRegistrosSanitarios_editar",
                    "vRegistrosSanitarios_eliminar",
                    "vDocumentos",
                    "vDocumentos_crear",
                    "vDocumentos_editar",
                    "vDocumentos_eliminar",
                    "vCajaAperturas",
                    "vCajaAperturas_aperturarCaja",
                    "vCajaAperturas_ver",
                    "vCajaAperturas_cerrarCaja",
                    "vCajaAperturas_eliminar",
                    "vCajaMovimientos",
                    "vCajaMovimientos_crear",
                    "vCajaMovimientos_editar",
                    "vCajaMovimientos_eliminar",
                    "vMonedas",
                    "vMonedas_crear",
                    "vMonedas_editar",
                    "vMonedas_eliminar",
                    "vTipoCambios",
                    "vTipoCambios",
                    "vTipoCambios_crear",
                    "vTipoCambios_editar",
                    "vTipoCambios_eliminar",
                    "vMaquinas",
                    "vMaquinas_crear",
                    "vMaquinas_editar",
                    "vMaquinas_eliminar",
                    "vEquipos",
                    "vEquipos_crear",
                    "vEquipos_editar",
                    "vEquipos_eliminar",
                    "vColaboradores",
                    "vColaboradores_crear",
                    "vColaboradores_editar",
                    "vColaboradores_eliminar"
                ]
            }
        ])

        console.log('Datos iniciales creados con éxito.')
    }
    catch (error) {
        console.error('Error al inicializar datos:', error)
    }
}

export default initData